/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TargetRouteImport } from './routes/target'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TargetRoute = TargetRouteImport.update({
  id: '/target',
  path: '/target',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/calculator': typeof CalculatorRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/payment': typeof PaymentRoute
  '/process': typeof ProcessRoute
  '/signup': typeof SignupRoute
  '/target': typeof TargetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/calculator': typeof CalculatorRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/payment': typeof PaymentRoute
  '/process': typeof ProcessRoute
  '/signup': typeof SignupRoute
  '/target': typeof TargetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/calculator': typeof CalculatorRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/payment': typeof PaymentRoute
  '/process': typeof ProcessRoute
  '/signup': typeof SignupRoute
  '/target': typeof TargetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply'
    | '/calculator'
    | '/leads'
    | '/login'
    | '/menu'
    | '/payment'
    | '/process'
    | '/signup'
    | '/target'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply'
    | '/calculator'
    | '/leads'
    | '/login'
    | '/menu'
    | '/payment'
    | '/process'
    | '/signup'
    | '/target'
  id:
    | '__root__'
    | '/'
    | '/apply'
    | '/calculator'
    | '/leads'
    | '/login'
    | '/menu'
    | '/payment'
    | '/process'
    | '/signup'
    | '/target'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplyRoute: typeof ApplyRoute
  CalculatorRoute: typeof CalculatorRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  MenuRoute: typeof MenuRoute
  PaymentRoute: typeof PaymentRoute
  ProcessRoute: typeof ProcessRoute
  SignupRoute: typeof SignupRoute
  TargetRoute: typeof TargetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/target': {
      id: '/target'
      path: '/target'
      fullPath: '/target'
      preLoaderRoute: typeof TargetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplyRoute: ApplyRoute,
  CalculatorRoute: CalculatorRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  MenuRoute: MenuRoute,
  PaymentRoute: PaymentRoute,
  ProcessRoute: ProcessRoute,
  SignupRoute: SignupRoute,
  TargetRoute: TargetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
