/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as TargetRouteImport } from './routes/target'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const TargetRoute = TargetRouteImport.update({
  id: '/target',
  path: '/target',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/target': typeof TargetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/target': typeof TargetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/target': typeof TargetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/leads' | '/login' | '/payment' | '/target'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/leads' | '/login' | '/payment' | '/target'
  id: '__root__' | '/' | '/leads' | '/login' | '/payment' | '/target'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  PaymentRoute: typeof PaymentRoute
  TargetRoute: typeof TargetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/target': {
      id: '/target'
      path: '/target'
      fullPath: '/target'
      preLoaderRoute: typeof TargetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  PaymentRoute: PaymentRoute,
  TargetRoute: TargetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
